name: CI

on:
  pull_request:
    branches: [master]
  workflow_call:
    outputs:
      commit:
        description: "Short Commit Id"
        value: ${{ jobs.build-and-push.outputs.commit }}
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    outputs:
      commit: ${{ steps.push-image.outputs.commit }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - if: github.event_name != 'pull_request'
        name: Push Docker Image
        id: push-image
        run: |
          echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          # Get Short commit id
          VERSION=${GITHUB_SHA::8}
          echo IMAGE_NAME=$IMAGE_NAME
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_NAME:$VERSION 
          docker push $IMAGE_NAME:$VERSION
          docker push $IMAGE_NAME
          echo "::set-output name=commit::$VERSION"
      - if: github.event_name != 'pull_request'
        name: Publish Deployment Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: deployment-artifacts
          path: |
            deployment