name: CI_CD

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 2
      matrix:
        environment: [ Dev ]
        region: [ us-east-2 ]
    environment:
      name: ${{ matrix.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ matrix.region }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Deploy Helm
        uses: bitovi/github-actions-deploy-eks-helm@v1.2.8
        with:
          aws-region: ${{ matrix.region }}
          cluster-name: ${{ secrets.AWS_CLUSTER_NAME }}
          name: hello-world
          chart-path: helm


