name: CI

on:
  pull_request:
    branches: [master]
  workflow_call:
    outputs:
      commit:
        description: "Short Commit Id"
        value: ${{ jobs.build-and-push.outputs.commit }}
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    outputs:
      commit: ${{ steps.push-image.outputs.commit }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/<your-GitHub-username>/docker-example:latest
          docker push ghcr.io/<your-GitHub-username>/docker-example:latest
